apiVersion: v1
kind: Service
metadata:
  name: public-lb
  labels:
    app: kabnodejsdemo
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-enable-features: "proxy-protocol"
    service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: public
spec:
  type: LoadBalancer
  selector:
    app: kabnodejsdemo
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080